dijkstra法のチートシートの追加
koher/swift-atcoder-support pull request #2
Opened 2020-10-18 08:52 UTC by akTARDIGRADE13

最適化できたので再PRします。計算量**O((V+E)logV)**で動くと思います。
改善点があれば、指摘していただけると嬉しいです。
よろしくお願いします<(_ _)>

2020-10-18 08:54 UTC, akTARDIGRADE13 commented
懸念材料だったプライオリティーキューの実装については、下記の記事から引用させていただきました。
[競プロ用優先度付きキュー(Priority Queue) in Swift](https://qiita.com/conf8o/items/a89ce80d5b7a51550a33)
また、ダイクストラ法は、昔Pythonで書いたチートシートと蟻本を参考に作成しました。

2020-10-18 14:53 UTC, koher requested changes
他に相談したいことはあるんですが、ひとまず変更が必要そうな箇所についてコメントしました。

2020-10-18 14:53 UTC, koher commented on Sources/AtCoderSupport/dijkstra.swift
> +    init<Seq: Sequence>(_ seq: Seq, _ order: @escaping (T, T) -> Bool) where Seq.Element == T {
このような関数／メソッドローカルの型パラメータは一文字が使われることが多いので `Seq` を `S` に変更お願いします。

引数名 `seq` は、 Swift では省略せずに `sequence` とする方が一般的なので `seq` → `sequence` が良いと思います。 AtCoder ではコード長に制限がありますが、 512 KiB は実質的に問題にならないと思うので。また、コード長については成績に関係ないという認識です。もし僕の認識違いならご指摘下さい:bow:

2020-10-18 14:53 UTC, koher commented on Sources/AtCoderSupport/dijkstra.swift
> +func dijkstra(graph:[[[Int]]],start:Int)->[Int]{
- 距離については `Int` とは限らないので、任意の `Distance` を取りたいです。
- `[iに隣接する頂点j, 辺の重み]` はわかりづらいので、 `(index: Int, distance: Distance)` というタプルにするのが良いと思います。
- `start` は [TSP](https://github.com/koher/swift-atcoder-support/blob/main/Sources/AtCoderSupport/TSP.swift) などと統一して `startedAt` というラベルで引数名は `start` でお願いします。

総合すると、↓のようなシグネチャにするのが良いと思います。

```swift
func dijkstra<Distance>(graph: [[(index: Int, distance: Distance)]], startedAt start: Int) -> [Int] where Distance: Comparable, Distance: AdditiveArithmetic
```

2020-10-18 14:53 UTC, koher commented on Sources/AtCoderSupport/dijkstra.swift
> +    var dist = Array(repeating: INF, count: graph.count) // 各ノードの頂点からの最短距離
距離を `Distance` で扱うことにしたため、 `INF` が使えないです。ここは悩ましいですが、

- `[Distance?]` にして `nil` を無限扱いにする
- 引数として `infinity` を渡すようにする
- `Distance` が `FixedWidthInteger` と `FloatingPoint` に適合する場合のオーバーロードを作る

のどれかかなぁと思います。 `Optional` を使うことのパフォーマンスへの影響は無視できる程度ではないかと思うのでまずそれをやってみて、ベンチマークを取って無視できなかったときに他の方法を検討するのが良いかなと思います。

2020-10-18 14:53 UTC, koher commented on Sources/AtCoderSupport/dijkstra.swift
> +struct PriorityQueue<T> {
Swift では型の持つ型パラメータは `T` のような一文字ではなく `Element` のようなフルの名前を付けることが一般的なので、 `T` → `Element` でお願いします。

2020-10-18 14:53 UTC, koher commented on Sources/AtCoderSupport/dijkstra.swift
> +    public var isEmpty: Bool {
`PriorityQueue` 自体のアクセスレベルが `internal` なので、 `public` は不要で↓で良いと思います。

```swift
var isEmpty: Bool {
```

`PriorityQueue` の他の API も同様です。

2020-10-18 15:07 UTC, koher commented
@akTARDIGRADE13 

> 懸念材料だったプライオリティーキューの実装については、下記の記事から引用させていただきました。

こちらのコードはライセンス不明なので、 [CC0](https://github.com/koher/swift-atcoder-support/blob/main/LICENSE) のこのリポジトリにそのまま組み込むのは難しいように思います。また、↑でコメントしたように色々と修正が必要そうなので、 `PriorityQueue` についてはこちらで実装してみようかなと思います。

あと、ダイクストラ法の実装について詳しくないんですが、 `PriorityQueue` の代わりに赤黒木とかで実装された [`SortedSet`](https://docs.oracle.com/javase/jp/8/docs/api/java/util/SortedSet.html) とかでも良さそうな気がするんですけど、パフォーマンスの問題でこの `PriorityQueue` のような実装が好ましいのでしょうか？

併せて相談したいんですが、このリポジトリのコードはコピペを前提としているので、コピペの単位でひとまとめにしておきたいんですが、 `PriorityQueue` は競プロ上、ダイクストラ法でしかほぼ利用されないものですか？それとも、他のケースでも利用されることが多いものでしょうか？後者の場合でも、汎用的な `PriorityQueue` とは別に、（たとえ二重メンテになったとしても）ダイクストラ法用の `PriorityQueue` はこのファイル中に `private` で実装しておいてまとめてコピペできるようにしておくのが良いと思うのですがいかがでしょうか？

2020-10-18 22:05 UTC, akTARDIGRADE13 commented
ひとまず指摘いただいた点については、こちらで修正したいと思います。Qiitaの方だけ更新して、Githubの方はkoher 様にお願いするという形でよろしいでしょうか？

>また、↑でコメントしたように色々と修正が必要そうなので、 <code>PriorityQueue</code> についてはこちらで実装してみようかなと思います。

了解しました。ライセンスのことまで気が回らず、申し訳ありません。よろしくお願いします。



><code>SortedSet</code> は重複を許さないからダメでしょうか？

恥ずかしながら <code>SortedSet</code> というものを初めて聞きました。重複を許さない <code>PriorityQueue</code> という認識であっているでしょうか。
ダイクストラ法で使うのであれば、ほとんどの場合 <code>SortedSet</code> で十分なように思います。ただ、「存在する最短路をすべて出力せよ」というようなやや特殊な経路復元の問題だと、重複を許してくれないのはまずそうです (こんな問題があるかどうかはわかりませんが) 。


>併せて相談したいんですが、このリポジトリのコードはコピペを前提としているので、コピペの単位でひとまとめにしておきたいんですが、 <code>PriorityQueue</code> は競プロ上、ダイクストラ法でしかほぼ利用されないものですか？

ダイクストラ法以外で必要となる場面はあまりないです。ですが、皆無というわけでもなく、<code>PriorityQueue</code> がないと実装に困るような問題もたまに見かけます。

>後者の場合でも、汎用的な <code>PriorityQueue</code> とは別に、（たとえ二重メンテになったとしても）ダイクストラ法用の <code>PriorityQueue</code> はこのファイル中に <code>private</code> で実装しておいてまとめてコピペできるようにしておくのが良いと思うのですがいかがでしょうか？

賛成です！その方が便利ですし、使う側としてはとても嬉しいと思います。

2020-10-19 01:29 UTC, koher commented
Priority Queue を実現するための[二分ヒープ](https://ja.wikipedia.org/wiki/%E4%BA%8C%E5%88%86%E3%83%92%E3%83%BC%E3%83%97)について調べてみましたが、二分探索木と比べて次のような利点がありそうです。

- 配列で実装できる（高パフォーマンス）
- 平衡木である（最悪計算量のオーダーが小さい）
- 追加が速い（平均計算量O(1) ）

当然その分の犠牲はあって、二分探索木は全ノードがソートされているのに対して、二分ヒープでは先頭のノードが最小（または最大）であることが保証されているだけで、イテレートしてソートされた順にアクセスすることはできないという違いがありそうです。単純な二分探索木との比較ですら二分ヒープの方が高速で、赤黒木のような平衡二分探索木はさらに複雑な操作を行っているので、ダイクストラ法の用途では二分ヒープ等を使って探索木ではなく Priority Queue として実装するのが速そうです。

[フィボナッチヒープ](https://ja.wikipedia.org/wiki/%E3%83%95%E3%82%A3%E3%83%9C%E3%83%8A%E3%83%83%E3%83%81%E3%83%92%E3%83%BC%E3%83%97)はより高速なようなので、ひとまずは二分ヒープでマージした後で将来的に Priority Queue の実装を差し替えても良いかもしれません。

> フィボナッチヒープはグラフ内で最短経路を計算するためのダイクストラ法や、グラフの最小全域木を計算するプリム法のおおよその処理時間を改善するのに用いられる。
> -- [フィボナッチヒープ](https://ja.wikipedia.org/wiki/%E3%83%95%E3%82%A3%E3%83%9C%E3%83%8A%E3%83%83%E3%83%81%E3%83%92%E3%83%BC%E3%83%97)

2020-10-19 13:13 UTC, akTARDIGRADE13 commented
フィボナッチヒープですか！初耳です。
ひとまずは二分ヒープで…とのことですが、具体的に僕は何をしたらよろしいでしょうか？
このPRもどのように処理していいのかよくわかっていないです…。
素人質問で申し訳ありません。

2020-10-19 14:55 UTC, koher commented
@akTARDIGRADE13 

#3 で `PriorityQueue` を実装してみたのでレビューしてもらっても大丈夫ですか？

#3 を開いてまずメッセージを読んでいただき、 "Files changed" タブをクリックすると差分を確認できるので、コードを見て問題がないかチェックして下さい。 `dijkstra` 関数で利用するのに問題なさそうかをチェックしてもらえれば十分なので、実装の詳細まで確認していただかなくて大丈夫です。パフォーマンスについては、元のこの PR の `PriorityQueue` より速いことを確認済みです。

特に問題なさそうであれば右上の緑の "Review changes" ボタンから "Leave a comment" のテキストエリアに "LGTM" とでも書いて "Approve" を選択し、 "Submit Review" ボタンを押して下さい。

問題がありそうな箇所があれば、コード中の行頭の "+" をクリックしてコメントを追加し、 "Start a review" ボタンを押して下さい。同じ要領で複数のコメントを追加できます。コメントを追加し終わったら、右上の緑の "Finish your review" ボタンを押してから "Request changes" を選択し、（総論としてコメントすることがあれば "Leave a comment" にコメントを入力し、） "Submit review" ボタンを押して下さい。

2020-10-19 15:00 UTC, koher commented
@akTARDIGRADE13 

> 具体的に僕は何をしたらよろしいでしょうか？

ひとまず、

> 指摘いただいた点については、こちらで修正したいと思います。

とのことですので、（ `PriorityQueue` はこちらで実装したので） `dijkstra` に関する修正をお願いできますか？修正できたら @akTARDIGRADE13 さんが fork したリポジトリの `add-new-file` ブランチに push してもらえれば、自動的にこの PR に反映されると思います。

その上で、 #3 のマージが終わったら、 `PriorityQueue` をこちらにも反映しましょうか。（それはまたそのときになったら説明します。）

2020-10-21 18:05 UTC, koher commented
続きを引き継ぐことになりましたが、このブランチには僕は push できないため、この PR は close して #4 に引き継ぎます。

2020-10-21 18:05 UTC, closed without merging